### ISSUE TITLE
CursorIndexOutOfBoundsException

### ISSUE THREAD

**Issue by lingling-fan** [wistein/TourCount#12]
//package name: com.wmstein.tourcount
//version: 2.1.4
 java.lang.RuntimeException: Unable to resume activity {com.wmstein.tourcount/com.wmstein.tourcount.EditIndividualActivity}: android.database.CursorIndexOutOfBoundsException: Index 0 requested, with a size of 0
 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2790)
 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2819)
 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2266)
 	at android.app.ActivityThread.access$600(ActivityThread.java:141)
 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
 	at android.os.Handler.dispatchMessage(Handler.java:99)
 	at android.os.Looper.loop(Looper.java:137)
 	at android.app.ActivityThread.main(ActivityThread.java:5103)
 	at java.lang.reflect.Method.invokeNative(Native Method)
 	at java.lang.reflect.Method.invoke(Method.java:525)
 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
 	at dalvik.system.NativeStart.main(Native Method)
 Caused by: android.database.CursorIndexOutOfBoundsException: Index 0 requested, with a size of 0
 	at android.database.AbstractCursor.checkPosition(AbstractCursor.java:424)
 	at android.database.AbstractWindowedCursor.checkPosition(AbstractWindowedCursor.java:136)
 	at android.database.AbstractWindowedCursor.getInt(AbstractWindowedCursor.java:68)
 	at com.wmstein.tourcount.database.IndividualsDataSource.cursorToIndividuals(IndividualsDataSource.java:87)
 	at com.wmstein.tourcount.database.IndividualsDataSource.getIndividual(IndividualsDataSource.java:150)
 	at com.wmstein.tourcount.EditIndividualActivity.onResume(EditIndividualActivity.java:154)
 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1192)
 	at android.app.Activity.performResume(Activity.java:5211)
 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2780)

**Comment by lingling-fan** [comment]
**Pkg**: com.wmstein.tourcount
**Exception**: android.database.CursorIndexOutOfBoundsException: Index 0 requested, with a size of 0
**Category**: Index error
**Root cause**: The cursor in Method "com.wmstein.tourcount.database.IndividualsDataSource.getIndividual(at line 150)" has not check if the access line exists or not, missing "if (cursor.moveToFirst())" probably.
**Description**: When querying database, it may failed, better to check whether the return value is null or not; Besides, the cursor is at index -1 by default, call "MoveToFirst()" before data access and also check if it's empty. 
Note: "null" and "empty" are different. 
**Fix solution**: 
    1: Use if((cursor != null) and (!cursor.MoveToFirst())) to check.
    2: Use while(!cursor.MoveToNext()) to iterate when using loop clause.

**Comment by wistein** [comment]
Thanks for your tests.
I will look into this asap. 

Please use the latest version and a provided example database as a starting point or create a new from scratch within the app.

Using an old database on a newer app version or vice versa will not work, as some tables were changed.

Older versions of the app should not be used anymore.

**Comment by wistein** [comment]
Fixed with commit 32585d7
