### ISSUE TITLE
NumberFormatException

### ISSUE THREAD

**Issue by lingling-fan** [wistein/TourCount#13]
//package name: com.wmstein.tourcount
//version: 2.1.4 / 2.1.3
 java.lang.NumberFormatException: Invalid int: " 0"
 	at java.lang.Integer.invalidInt(Integer.java:138)
 	at java.lang.Integer.parse(Integer.java:375)
 	at java.lang.Integer.parseInt(Integer.java:366)
 	at java.lang.Integer.parseInt(Integer.java:332)
 	at com.wmstein.tourcount.widgets.EditMetaWidget.getWidgetTemp2(EditMetaWidget.java:178)
 	at com.wmstein.tourcount.EditMetaActivity.saveData(EditMetaActivity.java:257)
 	at com.wmstein.tourcount.EditMetaActivity.onOptionsItemSelected(EditMetaActivity.java:303)
 	at android.app.Activity.onMenuItemSelected(Activity.java:2566)
 	at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:403)
 	at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:189)
 	at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:100)
 	at android.support.v7.app.AppCompatDelegateImplV7.onMenuItemSelected(AppCompatDelegateImplV7.java:663)
 	at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:811)
 	at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
 	at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:958)
 	at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:948)
 	at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:618)
 	at android.support.v7.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:139)
 	at android.view.View.performClick(View.java:4240)
 	at android.view.View$PerformClick.run(View.java:17721)
 	at android.os.Handler.handleCallback(Handler.java:730)
 	at android.os.Handler.dispatchMessage(Handler.java:92)
 	at android.os.Looper.loop(Looper.java:137)
 	at android.app.ActivityThread.main(ActivityThread.java:5103)
 	at java.lang.reflect.Method.invokeNative(Native Method)
 	at java.lang.reflect.Method.invoke(Method.java:525)
 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
 	at dalvik.system.NativeStart.main(Native Method)

**Comment by wistein** [comment]
Fixed EditMetaWidget. Works now as expected in current version.
